import LocalizedStrings from "react-native-localization";

export const translations = new LocalizedStrings({
  en: {
    noLocationService: "Location Service Not Available",
    logout: "Logout",
    yes: "Yes",
    no: "No",
    cancel: "Cancel",
    areYouSure: "Are you sure?",
    logoutDesc: "You are about to log out, confirm?",
    noInternet: "No Internet Connection",
    numberOf: '60k+',
    premiumRecipe: ' Premium recipies',
    yummTitle: 'Yumm',
    findRecipe: 'Find the best recipes for cooking',
    signUp: 'Sign up',
    startCooking: 'Start cooking',
    sampleQty: '200 mg',
    ingredientsTitle: 'Ingredients',
    itemsTitle: 'Items',
    defaultRating: '4.5',
    defaultReviews: '300 Reviews',
    authorTitle: 'By Niki Samantha',
    locationTitle: 'Bali, Indonesia',
    followTitle: 'Follow',
    trendingTitle: 'Trending now 🔥',
    recentDefaultTitle: 'Indonesian chicken burger',
    recentDefaultDescription: 'By James Wolden',
    popularDefaultTitle: 'Indonesian chicken burger',
    recentTitle: 'Recent recipe',
    popularTitle: 'Popular creator',
    seeAll: 'See all',
    firstName: 'First name',
    lastName: 'Last name',
    firstNamePlaceHolder: 'Enter first name',
    lastNamePlaceHolder: 'Enter last name',
    emailPlaceHolder: 'Enter email',
    passwordPlaceHolder: 'Enter password',
    confirmPasswordPlaceHolder: 'Enter confirm password',
    email: 'Email',
    passwordTitle: 'Password',
    confirmPasswordTitle: 'Confirm password',
    guestTitle: 'Guest',
    goodTitle: 'Good ',
    morningTitle: 'morning',
    afternoonTitle: 'afternoon',
    eveningTitle: 'evening',
    searchRecipes: 'Search recipes',
    invalidDataTitle: 'Invalid Data',
    invalidDataMessage: 'Please enter valid data',
    errorFiledRequired: "Filed is required",
    errorInvalidEmail: "Enter valid email",
    tooShort: "Too short !",
    tooLong: "Too long !",
    missmatchPassword: 'Password miss match',
    welcomeMsg: "Good afternoon, {0}!",
    name: "By Niki Samantha" ,
    loading: "Loading...",
    savedRecipe: "Saved recipes",
    notifications: "Notifications",
    today: "Today",
    allSet: 'You’re all set!',
    myProfileTitle: "My profile",
    titleSignOut: "Sign out",
    msgSignOut: "Are you sure you want to logout!",
    tabVideos: "Videos",
    tabRecipies: "Recipies",
    bio: "Hello world I’m {0}, I’m from Italy 🇮🇹 I love cooking so much!",
    editProfile: "Edit Profile"
  },
});
