import type { ExtendedTheme } from "@react-navigation/native";
import { DefaultTheme } from "@react-navigation/native";

export const palette = {
  primary: "#33CDD7",
  secondary: "#00C1CD",
  background: "#f6f8fa",
  white: "#fff",
  black: "#101214",
  button: "#1c1e21",
  shadow: "#757575",
  text: "#30363b",
  borderColor: "#d0d7de",
  borderColorDark: "#333942",
  placeholder: "#a1a1a1",
  danger: "rgb(208, 2, 27)",
  title: "rgb(102, 102, 102)",
  separator: "rgb(194, 194, 195)",
  highlight: "rgb(199, 198, 203)",
  blackOverlay: "rgba(0,0,0,0.6)",
  iconWhite: "#fff",
  iconBlack: "#101214",
  dynamicWhite: "#fff",
  dynamicBlack: "#1c1e21",
  dynamicBackground: "#fff",
  transparent: "transparent",
  calpyse: "#2b7488",
  secondaryWhite: "#f1f1f1",
  secondaryBlack: "#130F26",
  neutralBlack: "#181818",
  grey: "#303030",
  grey4D: "#3030304D",
  secondaryGrey: "#D9D9D9",
  lightGrey: "#A9A9A9",
  orange: "#FFB661",
  startBlack: "rgba(0,0,0,0)", 
  endBlack: "rgba(0,0,0,0.9)",
  error: '#FF0000',
  inputTextColor: '#C1C1C1',
  cardBackground: "rgba(0, 0, 0, 0.1)",
  veryLightGrey: "#797979",
  notificationTitle: "#303030",
  inputBg: "#f0f0f0",
  inputBorder: "#ddd",
  disableBtn: "#A5C9CA"
};

export const LightTheme: ExtendedTheme = {
  dark: false,
  colors: {
    ...DefaultTheme.colors,
    ...palette,
  },
};

export const DarkTheme: ExtendedTheme = {
  ...DefaultTheme,
  colors: {
    ...LightTheme.colors,
    background: palette.black,
    foreground: palette.white,
    text: palette.white,
    tabBar: palette.black,
    iconWhite: palette.black,
    iconBlack: palette.white,
    dynamicBackground: palette.dynamicBlack,
    shadow: palette.transparent,
    borderColor: palette.borderColorDark,
    startBlack:  palette.startBlack, 
    endBlack: palette.endBlack,
    error: palette.error,
    grey: palette.white,
    secondaryGrey: palette.secondaryGrey,
    inputTextColor: palette.inputTextColor,
    cardBackground: 'rgba(255, 255, 255, 0.6)',
    veryLightGrey: palette.veryLightGrey,
    notificationTitle: palette.grey,
    inputBg: palette.inputBg,
    inputBorder: palette.inputBorder,
    disableBtn: palette.disableBtn
  },
};
